### ISSUE TITLE
Replay diverges

### ISSUE THREAD

**Issue by ejpbruel** [mozilla/rr#1841] opened 2016-10-05 14:26 UTC
Steps to reproduce:
1. Create a recording with rr, performing the following steps:
  a. Open a recent build of Firefox Nightly.
  b. Open the webconsole
  c. Evaluate the following string in the webconsole:

```
var iframe = document.createElement('iframe');
iframe.sandbox = 'allow-scripts';
iframe.src = 'data:text/html,<!doctype html><script>'
    + 'var f = function(){}; f.a=1; console.log(f);<\/script>';
document.body.appendChild(iframe);
```

  d. Click on the logged function in the console
  e. Close Firefox Nightly.

(see bug https://bugzilla.mozilla.org/show_bug.cgi?id=1281875 for details)
1. Replay the recording with rr.
2. Set a breakpoint in DebuggerObject::getOwnPropertyNames (Debugger.cpp:9718)
3. Continue the replay.

Expected results:
The breakpoint should trigger when we click on the logged function in the console.

Actual results:
I get the following error:
[ERROR /home/ejpbruel/Projects/rr/src/ReplaySession.cc:507:guard_overshoot() errno: SUCCESS] Replay diverged; target registers mismatched: 
[FATAL /home/ejpbruel/Projects/rr/src/ReplaySession.cc:511:guard_overshoot() errno: SUCCESS]

Note: unlike the previous issue I opened, I made sure to do pull from the rr repo and do a fresh build first. The version of rr I'm using is currently 4.4.0.

**Comment by rocallahan** [comment] 2016-10-10 02:26
I couldn't reproduce the bug following those instructions ... but thanks for providing them!

If you replay with `rr replay -a`, does the replay succeed or fail? If that fails, there's probably some extra information in the output; can you dump that here, along with the last several events from `rr dump -b -m -p` leading up to the reported failed event number? Thanks!!!

**Comment by khuey** [comment] 2019-07-07 21:56
I'm going to close this as unlikely to go anywhere.

**Closed by khuey** 2019-07-07 21:56 UTC
