### ISSUE TITLE
 -> Assertion `decoded.modifies_flags || iterations <= BYTES_COALESCED' failed to hold. 

### ISSUE THREAD

**Issue by glandium** [mozilla/rr#1842] opened 2016-10-06 09:07 UTC
```
(rr) reverse-next
[FATAL /build/rr-2TXu21/rr-4.4.0/src/fast_forward.cc:326:fast_forward_through_instruction() errno: SUCCESS] 
 (task 27661 (rec:27366) at time 22112)
 -> Assertion `decoded.modifies_flags || iterations <= BYTES_COALESCED' failed to hold. 
```
(this is from rr 4.4 from Debian unstable)

Please tell me what additional information you'd need.

**Comment by rocallahan** [comment] 2016-10-10 02:29
In the emergency debugger `disasm` should show the string instruction being performed, that'd be useful. Plus the register dump from the emergency debugger. In rr itself, the values of `cur_cx`, `iterations`, `iterations_performed`. Thanks!

**Comment by glandium** [comment] 2016-10-11 06:55
String instruction being performed:
```
=> 0x00007f71442cfcdf <+79>:	rep movsb %ds:(%rsi),%es:(%rdi)
```

Registers:
```
rax            0x2179d14	35101972
rbx            0xffffffffffffe027	-8153
rcx            0x16e	366
rdx            0x1fef	8175
rsi            0x217bca0	35110048
rdi            0x217bb95	35109781
rbp            0x21657d0	0x21657d0
rsp            0x7ffc2f550db8	0x7ffc2f550db8
r8             0x2177c6c	35093612
r9             0x2179c19	35101721
r10            0x2179c19	35101721
r11            0x1	1
r12            0x217bdd0	35110352
r13            0x2177c60	35093600
r14            0x2	2
r15            0x3	3
rip            0x7f71442cfcdf	0x7f71442cfcdf <__memmove_avx_unaligned_erms+79>
eflags         0x10297	[ CF PF AF SF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
```

In rr:
```
(gdb) print cur_cx
$1 = 8174
(gdb) print iterations
$2 = 365
(gdb) print iterations_performed
$3 = 7808
```

**Comment by rocallahan** [comment] 2016-10-11 09:30
Can you print `t->get_siginfo()` in rr? Also `watch_di` and `watch_offset`.

**Comment by rocallahan** [comment] 2016-10-11 09:35
And `triggered_watchpoint`.

This looks like an overlapping `memmove`, so maybe we're triggering a watchpoint early via RSI. That does look like it could be a bug, an invalid assertion in this case,

**Comment by glandium** [comment] 2016-10-11 12:01
```
(gdb) print watch_di
$5 = {ptr = 35110017}
(gdb) print watch_offset 
$6 = 8044
(gdb) print triggered_watchpoint 
$7 = true
(gdb) set print pretty
(gdb) print t->get_siginfo()
$8 = (const siginfo_t &) @0x1f0a390: {
  si_signo = 5, 
  si_errno = 0, 
  si_code = 4, 
  _sifields = {
    _pad = {1143799007, 32625, 89, 0, 32548752, 0, 32550224, 0, 32549504, 0, 32548128, 0, -686981120, 32701, -684888064, 32701, 
      -686981120, 32701, -684888064, 32701, 32548032, 0, 34, 0, 34, 0, 0, 0}, 
    _kill = {
      si_pid = 1143799007, 
      si_uid = 32625
    }, 
    _timer = {
      si_tid = 1143799007, 
      si_overrun = 32625, 
      si_sigval = {
        sival_int = 89, 
        sival_ptr = 0x59
      }
    }, 
    _rt = {
      si_pid = 1143799007, 
      si_uid = 32625, 
      si_sigval = {
        sival_int = 89, 
        sival_ptr = 0x59
      }
    }, 
    _sigchld = {
      si_pid = 1143799007, 
      si_uid = 32625, 
      si_status = 89, 
      si_utime = 32548752, 
      si_stime = 32550224
    }, 
    _sigfault = {
      si_addr = 0x7f71442cfcdf, 
      si_addr_lsb = 89, 
      si_addr_bnd = {
        _lower = 0x1f0a790, 
        _upper = 0x1f0ad50
      }
    }, 
    _sigpoll = {
      si_band = 140124451831007, 
      si_fd = 89
    }, 
    _sigsys = {
      _call_addr = 0x7f71442cfcdf, 
      _syscall = 89, 
      _arch = 0
    }
  }
}
```

**Comment by rocallahan** [comment] 2016-10-11 20:38
Thanks. I can reproduce this in a testcase.

**Comment by rocallahan** [comment] 2016-10-11 20:42
Fixed by https://github.com/mozilla/rr/commit/dd8bcb4bfe92b3bf99e2379d9669002ff2be4bc5

**Closed by rocallahan** 2016-10-11 20:42 UTC

**Comment by glandium** [comment] 2016-10-15 10:29
I can confirm this is fixed. Thanks.
