### ISSUE TITLE
rr CMakeLists.txt does not pick up `pexpect` on Ubuntu 18.04

### ISSUE THREAD

**Issue by acgetchell** [mozilla/rr#2350] opened 2019-05-02 15:50 UTC
```
┌─[adam][ubuntu][~]
└─▪ git clone https://github.com/mozilla/rr.git
Cloning into 'rr'...
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 33654 (delta 50), reused 54 (delta 33), pack-reused 33553
Receiving objects: 100% (33654/33654), 18.88 MiB | 4.19 MiB/s, done.
Resolving deltas: 100% (25235/25235), done.
┌─[adam][ubuntu][~]
└─▪ mkdir obj && cd obj
┌─[adam][ubuntu][~/obj]
└─▪ cmake ../rr
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'capnp'
--   Found capnp, version 0.6.1
-- Found PythonInterp: /home/linuxbrew/.linuxbrew/bin/python3 (found suitable version "3.7.3", minimum required is "3.0") 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pexpect'
CMake Error at CMakeLists.txt:287 (message):
  Couldn't find required Python module pexpect.


-- Configuring incomplete, errors occurred!
See also "/home/adam/obj/CMakeFiles/CMakeOutput.log".
┌─[adam][ubuntu][~/obj]
└─▪ sudo apt-get install ccache cmake make g++-multilib gdb pkg-config coreutils python3-pexpect manpages-dev git ninja-build capnproto libcapnp-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ccache is already the newest version (3.4.1-1).
cmake is already the newest version (3.10.2-1ubuntu2).
coreutils is already the newest version (8.28-1ubuntu1).
gdb is already the newest version (8.1-0ubuntu3).
libcapnp-dev is already the newest version (0.6.1-1ubuntu1).
make is already the newest version (4.1-9.1ubuntu1).
manpages-dev is already the newest version (4.15-1).
pkg-config is already the newest version (0.29.1-0ubuntu2).
python3-pexpect is already the newest version (4.2.1-1).
capnproto is already the newest version (0.6.1-1ubuntu1).
ninja-build is already the newest version (1.8.2-1).
g++-multilib is already the newest version (4:7.4.0-1ubuntu2.2).
git is already the newest version (1:2.17.1-1ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by khuey** [comment] 2019-05-02 15:51
Please don't file multiple issues.

Dupe of #2348

**Closed by khuey** 2019-05-02 15:51 UTC

**Comment by acgetchell** [comment] 2019-05-02 15:58
Please address the issue.

```sudo apt-get install ccache cmake make g++-multilib gdb pkg-config coreutils python3-pexpect manpages-dev git ninja-build capnproto libcapnp-dev```

Is directly out of your instructions.

https://github.com/mozilla/rr/wiki/Building-And-Installing

Which do not work.

**Comment by khuey** [comment] 2019-05-02 18:20
As I said in the other issue, those instructions do not work because you are not using your standard system python.

You either need to install pexpect in the linuxbrew python or get rr's CMake script to find the system python (by making sure it is first on your PATH).
