### ISSUE TITLE
Running the dom/media/tests/mochitest tests under rr fails

### ISSUE THREAD

**Issue by khuey** [mozilla/rr#1534] opened 2015-07-30 23:37 UTC
It appears a dup is failing unexpectedly in shared_memory_posix.cc and then Firefox aborts.  I didn't investigate further.

**Comment by rocallahan** [comment] 2015-08-07 10:55
I think we're hitting https://bugzilla.mozilla.org/show_bug.cgi?id=1126078. rr consumes extra fds during recording so we'd hit that bug more quickly under rr.

Interestingly, during replay of that same trace we also hit the limit. That may be fixable in rr since we shouldn't need many fds open during replay.

**Comment by rocallahan** [comment] 2015-08-07 12:08
During replay, the problem is EmuFs. Every shared segment present in every ReplaySession consumes one fd in rr (because it's a nameless temporary file and we want to be able to easily reopen it). So when a session has lots of shared segments open (> 500 in this case!), and we make many checkpoints of that session, we easily exhaust the fd limit in rr.

**Comment by rocallahan** [comment] 2015-08-18 04:34
While looking into bug 1126078, I actually found an rr bug. We were checking for `MSG_DONTWAIT` incorrectly in `sendmsg` and that was causing Chromium IPC code to context-switch unnecessarily while sending messages. With that fixed, I can no longer reproduce failures in `test_ipc.html` which I could easily reproduce before.

Fixed by 8e66e9f98783045483031708c8cd2846564de2e3.

**Closed by rocallahan** 2015-08-18 04:34 UTC
