### ISSUE TITLE
Many test failures on VMWare Fusion 8.5.3; reverse execution inoperable

### ISSUE THREAD

**Issue by lars-t-hansen** [mozilla/rr#1972] opened 2017-02-08 09:38 UTC
The host is a MacBook Pro ("Late 2013") with Mac OS 10.12.3 with 16GB RAM.
I'm running VMWare Fusion 8.5.3.
The guest machine is configured with 8GB RAM, four cores.
The guest OS is Ubuntu 16.04.1 64-bit.
rr sources are rev 3741bf0e1de760fed116425a0a59b50d23683bc4 (Feb 8 2017).
rr built with ninja as per instructions (using gcc 5.4.0).
I've enabled the performance counters in the prefs and in the vmx file as outlined on the install & build page.

Tests are still running and I'll attach the failure log when they're done, but there are numerous failures and timeouts, notably for watchpoints and reverse execution.  (But also some others.)

When I'm running rr replay, things start up fine and I can run to my crash but reverse execution then hangs (pinning one core, so it's ilooping, it's not stuck waiting for something).  Breaking out of the hang leaves an rr process running at 100% until I kill it.

When I start up the VM there's an error on the boot screen: ""the BIOS has corrupted hw-PMU resources (MSR 38d is 3)"  This appears to be a known issue (https://communities.vmware.com/thread/541258?start=0&tstart=0) though I've been unable to do anything about it.  So that may be the cause of the failures.  If you've seen this before I'll be grateful to hear any insights you have.

**Comment by rocallahan** [comment] 2017-02-08 09:43
> When I start up the VM there's an error on the boot screen: ""the BIOS has corrupted hw-PMU resources (MSR 38d is 3)"

I don't know anything about that.

Did you do this?
> Also add monitor_control.disable_hvsim_clusters = true to the VM's .vmx file

**Comment by lars-t-hansen** [comment] 2017-02-08 09:45
I did add that line to the file, and I just checked that it is still there.

**Comment by rocallahan** [comment] 2017-02-08 10:00
Hmm. This sounds mysterious. I think some people are able to use rr in Mac VMware successfully but I'm not sure. You might want to ask around at Mozilla.

It might be worth trying rr 4.4.0 or 4.3.0 to see if that works.

Your "BIOS corrupted" issue sounds interesting. It might be possible to determine what in MacOS is using PMU counters and maybe turn it off.

**Comment by lars-t-hansen** [comment] 2017-02-08 15:23
Failure log from 'ninja test' with the above configuration:  [failures-1.txt](https://github.com/mozilla/rr/files/761048/failures-1.txt)

(Will look into the PMU issue next.)

**Comment by lars-t-hansen** [comment] 2017-02-08 16:09
So far no resolution on the VM's BIOS error message.  The best guess, cf the web, is that the Mac uses some perf counters for power monitoring, but there's no hard information on that, nor on how to disable it.  (The advice for how to handle the problem is invariably "upgrade your BIOS and disable power monitoring".)  The web also believes this does not matter, it's just a spurious message from the vm's bios, but there's scant information to back that assertion up.

**Comment by rocallahan** [comment] 2017-02-08 19:44
Odd-looking set of test failures. A lot of the hard tests actually passed. Unfortunately the failure data for each test was not logged. Can you do something like
````
cd ~/rr/rr/sr/test
bash when.run -b ~/rr/rr ''
````
and then when it fails and prints some `/tmp/rr-test-...` path, dump that output and `/tmp/rr-test-.../gdb_rr.log`?

**Comment by sidkshatriya** [comment] 2017-04-07 10:31
I've been using Fusion 8.5.3 successfully on a Mac "Mid 2015" for sometime now. I also use Ubuntu 16.04

> the BIOS has corrupted hw-PMU resources

I always see this message on reboot. Its harmless I think cause its never led to any problems in record/replay.

The main question is: is this a single program that is giving you trouble with rr or _every_ program?

**Comment by agentzh** [comment] 2017-05-11 04:49
I'm seeing very similar test failures when running the today's rr master branch's build (commit 388856644) in the Fedora 24 guest OS run by my VMWare Fusion 8.5.6 on Mac OS X 10.11.6.

The laptop is a 15 inch Macbook Pro Retina mid-2015.

```
agentzh@fedora64 ~ $ rr --version
rr version 4.5.0
```

The first bunch of test failures are very similar to @lars-t-hansen's:

https://gist.github.com/agentzh/3c56d6b702e3fe38105f61f77d6e5d6b

I stopped the tests after running 782/2068, since it's way too slow.

The physical CPU is

```
agentzh@mbp15 ~ $ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
```
I have the following line in my virtual machine's `.vmx` file:

```
monitor_control.disable_hvsim_clusters = "TRUE"
```

I did a full guest OS reboot after updating this `.vmx` file.

More details about the guest OS:

```console
agentzh@fedora64 ~ $ cat /etc/fedora-release
Fedora release 24 (Twenty Four)

agentzh@fedora64 ~ $ uname -a
Linux fedora64 4.10.14-100.fc24.x86_64 #1 SMP Wed May 3 19:09:53 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

agentzh@fedora64 ~ $ gdb --version
GNU gdb (GDB) Fedora 7.11.1-86.fc24
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

agentzh@fedora64 ~ $ gcc --version
gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by agentzh** [comment] 2017-05-11 04:51
I'm just wondering whether using rr in a VMWare Fusion guest Linux is still a viable approach given all these test failures. Not sure about VMWare Workstation though. Don't have it atm.

**Comment by rocallahan** [comment] 2017-05-11 05:07
Apparently Fusion 8.5.3 was working for @sidkshatriya, which suggests Fusion 8.5.3 itself is not a deal-breaker. @sidkshatriya, what was your host OS version?

It seems probable there's some hardware or software configuration issue mucking things up here...

@agentzh, can you try https://github.com/mozilla/rr/issues/1972#issuecomment-278439816 ?

**Comment by agentzh** [comment] 2017-05-11 05:12
@rocallahan I've run the `no_mask_timeslice` test individually with verbose on:

https://gist.github.com/agentzh/ea3b81d20f344c3bcf2d2114063faf2f

Is that helpful?

**Comment by agentzh** [comment] 2017-05-11 05:26
@rocallahan Some more verbose output by individually running more test failures on my side:

* thread_yield

https://gist.github.com/agentzh/349780b131b27e45645181b3c96df96d
* breakpoint_overlap

https://gist.github.com/agentzh/05630ac8b73b59db3ba921f819ed9439
* clone_interruption

https://gist.github.com/agentzh/42f5dc6de8b766c59eb1be4a646b6af9
* goto_event

https://gist.github.com/agentzh/c79a7844b5bf6a33c702a2f80c1fdc4b

Hope these help. Please let me know if you need any further information. Thanks!

**Comment by agentzh** [comment] 2017-05-11 06:00
@rocallahan I tried to run `rr record` against my nginx program in my guest Fedora OS atop VMWware Fusion and immediately got an error:

```
1: Run... at b.pl line 7.
[FATAL /home/agentzh/git/rr/rr/src/record_syscall.cc:4617:rec_process_syscall_arch() errno: SUCCESS]
 (task 54944 (rec:54944) at time 819)
 -> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected ENOSYS for 'io_setup' but got result 0 (errno SUCCESS); execution of syscall unsupported by rr
```

The `errno SUCCESS` thing also appears in the rr test suite failure results mentioned above.

**Comment by rocallahan** [comment] 2017-05-11 06:44
Your nginx error is due to rr not currently supporting the async I/O syscalls. So that would need to be fixed in rr (or you could configure nginx to avoid using them, maybe).

**Comment by rocallahan** [comment] 2017-05-11 06:50
If you run `RR_LOG=RecordSession,RecordTask,Task rr record /home/agentzh/git/rr/obj/bin/thread_yield` what do you get?

**Comment by sidkshatriya** [comment] 2017-05-11 12:47
@rocallahan My host OS is macOS 10.12.4

**Comment by agentzh** [comment] 2017-05-11 16:11
@rocallahan This is strange. I've checked the output of strace and found no syscalls having the word "aio". And I've checked that nginx requires the explicit `./configure` option `--with-file-aio` to enable the native AIO support and my build never specifies that. What particular syscalls should I look for please? BTW, I tested the same nginx with the same configuration options in Ubuntu 16.04 running directly on my NUC and rr works flawlessly as far as I'm concerned.

Thanks for your time!

**Comment by agentzh** [comment] 2017-05-11 16:12
@sidkshatriya Did you successfully run the full rr test suite via `make test` or `make check` on your side?

**Comment by sidkshatriya** [comment] 2017-05-11 16:37
Not for a recent version of rr. But in the past (few months back) I've had 100% test success rate for rr.

**Comment by agentzh** [comment] 2017-05-11 17:16
@rocallahan Full output on Fedora 24 guest OS in VMWare Fusion 8.5.6 on Mac OS X 10.11.6 for the command `RR_LOG=RecordSession,RecordTask,Task rr record /home/agentzh/git/rr/obj/bin/thread_yield`:

https://gist.github.com/agentzh/43d1e743c151f7956f2a501341395338

Hope it helps.

Thanks!

**Comment by agentzh** [comment] 2017-05-11 17:19
@rocallahan Seems like gist does not show the full content by default. The true full version:

https://gist.githubusercontent.com/agentzh/43d1e743c151f7956f2a501341395338/raw/5bfca0a232ce6fab7caae34a12f539062f6d5374/a.txt

**Comment by rocallahan** [comment] 2017-05-11 20:47
> found no syscalls having the word "aio"

I believe the `aio_` functions are all libc helpers and the actual syscalls are `io_`, e.g. `io_setup` in this case.

When you hit that rr error mentioning `io_setup`, you should also get some instructions telling you how to run gdb to attach the emergency debugger. Follow them and get a backtrace from gdb via `where`. That should give you an nginx stack trace showing how it got to the point of calling `io_setup`.

**Comment by rocallahan** [comment] 2017-05-11 20:50
> The true full version:

Thanks. Can you also post the results of `rr dump -b -m -p` on that trace?

**Comment by agentzh** [comment] 2017-05-11 22:25
@rocallahan Regarding the aio thing, indeed you were right. I was misusing another nginx executable which does enable AIO. That gdb remote connect tip was very helpful. Thank you!

Now that I can successfully run `rr record` against my nginx program and reproduce a known crash. And then I can use `rr -M replay -a` to get the event ID for the assertion failure output. And then I can further use `rr -M replay -g <ID>` to jump to the assertion failure location and fetch the full C backtrace. So far so good! But when I add a breakpoint and try `reverse-cont`, it just hangs there and the `rr` process simply maxing out the CPU (100%) forever. I ran pstack and strace against that busy rr process, getting the following details:

https://gist.github.com/agentzh/cf0e1eae4e6c1bf9461c493e54c2ef46

How to debug this further? Thanks!

**Comment by agentzh** [comment] 2017-05-11 22:29
@rocallahan Hmm, seems like I'm having the same problem with `reverse-cont` as @lars-t-hansen. The symptoms are exactly the same. Also, my rr process is eating up memory (RES) while maxing out the CPU. After a few minutes, I had to kill it to avoid going OOM.

**Comment by agentzh** [comment] 2017-05-11 22:31
@rocallahan It is worth mentioning that the same nginx programs and rr operations do work beautifully in my Ubuntu 16.04 directly running on the NUC metal. So I guess it is VMWare and virtualization.

**Comment by rocallahan** [comment] 2017-05-11 22:34
I'd like to stay focused on the `thread_yield` failure since it's a small test and easier to understand. See https://github.com/mozilla/rr/issues/1972#issuecomment-300913023 : Can you also post the results of rr dump -b -m -p on that trace?

**Comment by agentzh** [comment] 2017-05-11 22:43
@rocallahan Since I just updated rr from the latest master (commit 3640251c9), I've rerun that `thread_yield` test:

https://gist.github.com/agentzh/5a7b671f627c3feb73e1a3320266ca63

And then run the command `_RR_TRACE_DIR=/tmp/rr-test-thread_yield-4bj8aTpO4 rr dump -b -m -p`, yielding

https://gist.github.com/agentzh/859c069749c016b21bcdcb8e3b5480c0

**Comment by agentzh** [comment] 2017-05-11 22:46
@rocallahan And for test 589:

https://gist.github.com/agentzh/ed583ae69f674932f0561c1371eb8bbe

**Comment by rocallahan** [comment] 2017-05-11 22:48
Ah OK the problem is actually obvious from the `rr dump`: all `ticks` values are zero. This indicates that the hardware performance counter is not working at all.

**Comment by rocallahan** [comment] 2017-05-11 22:52
Try `perf stat -e r5101c4 true` and see what you get.

**Comment by agentzh** [comment] 2017-05-11 23:03
@rocallahan Got this:

```
agentzh@fedora64 ~/git/rr/obj $ perf stat -e r5101c4 true

 Performance counter stats for 'true':

           109,029      r5101c4

       0.002176162 seconds time elapsed

```

**Comment by rocallahan** [comment] 2017-05-11 23:04
Hmm OK so perf events *are* working but not in rr.

**Comment by Keno** [comment] 2017-05-11 23:07
This kind of symptom happens when performance counters are oversubscribed on the host system.

**Comment by rocallahan** [comment] 2017-05-11 23:12
Interesting. @agentzh , try `perf stat -e r5101c4 -e r2005101c4 true`

**Comment by agentzh** [comment] 2017-05-11 23:20
@rocallahan See

```
agentzh@fedora64 ~ $ perf stat -e r5101c4 -e r2005101c4 true

 Performance counter stats for 'true':

           105,704      r5101c4
                 0      r2005101c4

       0.001579452 seconds time elapsed
```

**Comment by rocallahan** [comment] 2017-05-11 23:22
OK it looks like we only have one performance counter to play with. Which means we won't be able to support HLE/RTM and we won't be able to check if they're being used, but we can still detect this situation and proceed with a warning.

**Comment by agentzh** [comment] 2017-05-11 23:24
@rocallahan Interesting. Wondering whether there is a way to work around this limitation in the VMWare guest OS.

**Comment by rocallahan** [comment] 2017-05-11 23:26
In the guest, probably not. It must be some combination of VMWare and the host OS. IIRC the hardware has four counters and here three of them are being used by other software.

**Comment by Keno** [comment] 2017-05-11 23:28
The number of general purpose performance counters depends on the microarchitecture (and can even depend on BIOS settings - e.g. on KNL if you use 4 hyperthreads, each thread gets a quarter of the total counters).

**Comment by rocallahan** [comment] 2017-05-12 00:20
OK, https://github.com/mozilla/rr/commit/4a0894527f037e9fc156c7c6191e56d5cc56dbd7 should get us limping along with only one HW performance counter. Give it a try!

**Comment by rocallahan** [comment] 2017-05-12 00:22
Note that running tests in this configuration should work fine except for the `hle` tests, which should fail.

**Comment by agentzh** [comment] 2017-05-12 00:31
@rocallahan Wow, thread_yield is now passing fully with the latest git master version! Thanks!

I'll try running the full test suite shortly.

**Comment by agentzh** [comment] 2017-05-12 00:38
@rocallahan With the latest, rr, `video_capture` still fails one test:

https://gist.github.com/agentzh/51a2ad1a3ffb3bf591eb9e34335ff8d1

Is that expected?

**Comment by rocallahan** [comment] 2017-05-12 00:42
No. If there are only a few test failures I suggest we push that one off into a separate issue. (And try running the `video_capture` binary outside of rr to see if it works.)

**Comment by agentzh** [comment] 2017-05-12 00:46
@rocallahan OK, rerunning `video_capture` tests make them all pass now.

I've run the failed tests listed below and they all pass now with the latest rr:

https://gist.github.com/agentzh/3c56d6b702e3fe38105f61f77d6e5d6b

That is awesome! I'll run the full test suite in the next few hours.

**Comment by agentzh** [comment] 2017-05-12 01:28
@rocallahan I just tried rr to debug my own programs and reverse-cont now works as expected! Thanks!

**Comment by agentzh** [comment] 2017-05-12 02:28
For the record, with rr master commit 4a0894527, the result of a full test suite run gives me the following result in the Fedora 24 guest OS in VMWare Fusion:

```
99% tests passed, 1 tests failed out of 2068

Total Test time (real) = 3652.75 sec

The following tests FAILED:
        613 - video_capture (Failed)
Errors while running CTest
Makefile:149: recipe for target 'test' failed
make: *** [test] Error 8
```

Seems like `video_capture` could still fail intermittently.

Individually running `video_capture` again still passes for me:

```
$ ctest --verbose --tests-regex video_capture
UpdateCTestConfiguration  from :/home/agentzh/git/rr/obj/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/agentzh/git/rr/obj/DartConfiguration.tcl
Test project /home/agentzh/git/rr/obj
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 613
    Start 613: video_capture

613: Test command: /bin/bash "/home/agentzh/git/rr/rr/src/test/basic_test.run" "video_capture" "-b" "/home/agentzh/git/rr/obj" "120"
613: Test timeout computed to be: 1000
613: Test 'video_capture' PASSED
1/4 Test #613: video_capture ....................   Passed    0.13 sec
test 614
    Start 614: video_capture-no-syscallbuf

614: Test command: /bin/bash "/home/agentzh/git/rr/rr/src/test/basic_test.run" "video_capture" "-n" "/home/agentzh/git/rr/obj" "120"
614: Test timeout computed to be: 1000
614: Test 'video_capture' PASSED
2/4 Test #614: video_capture-no-syscallbuf ......   Passed    0.11 sec
test 1647
    Start 1647: video_capture-32

1647: Test command: /bin/bash "/home/agentzh/git/rr/rr/src/test/basic_test.run" "video_capture_32" "-b" "/home/agentzh/git/rr/obj"
1647: Test timeout computed to be: 1000
1647: Test 'video_capture_32' PASSED
3/4 Test #1647: video_capture-32 .................   Passed    0.12 sec
test 1648
    Start 1648: video_capture-32-no-syscallbuf

1648: Test command: /bin/bash "/home/agentzh/git/rr/rr/src/test/basic_test.run" "video_capture_32" "-n" "/home/agentzh/git/rr/obj"
1648: Test timeout computed to be: 1000
1648: Test 'video_capture_32' PASSED
4/4 Test #1648: video_capture-32-no-syscallbuf ...   Passed    0.11 sec

The following tests passed:
        video_capture
        video_capture-no-syscallbuf
        video_capture-32
        video_capture-32-no-syscallbuf

100% tests passed, 0 tests failed out of 4

Total Test time (real) =   0.51 sec
```

**Comment by rocallahan** [comment] 2017-05-12 02:33
Weird, but not worth worrying about I guess.

I'll call this fixed.

**Closed by rocallahan** 2017-05-12 02:33 UTC
