### ISSUE TITLE
Find CI infra with PMU support (to run real tests)

### ISSUE THREAD

**Issue by cgjones** [mozilla/rr#1433] opened 2015-03-06 05:33 UTC
Right now we run tests through travis-ci which I believe uses AWS on the backend.  We confirmed today that PMUs aren't available on EC/2.  Alternatives

* see if Azure or GCP or another virtual cloud vendor has PMU support
* cloud vendor that offers bare-metal instances
* local machine in someone's closet

All of these options will require ditching sweet simple travis-ci and setting up our own github hooks, but that's not too bad.  I think SW like Jenkins understands those out of the box.

**Comment by luser** [comment] 2015-03-23 11:44
Is there a simple way to test whether an environment supports PMUs?

**Comment by rocallahan** [comment] 2015-03-23 11:46
`perf list` and see if you get anything labelled `[Hardware event]`.

**Comment by khuey** [comment] 2015-03-23 14:14
So, FWIW, AWS and GCP do not have perf counters enabled, and Azure has AMD hardware.

**Comment by cgjones** [comment] 2015-03-23 19:46
(AMD PMUs are unsupported and some are broken.)

**Comment by cgjones** [comment] 2015-04-28 02:05
The kind JuliaLang folks found in JuliaLang/julia/#10952 that DigitalOcean offers machines with perf counter support.  Thanks!

**Comment by khuey** [comment] 2015-04-28 05:07
Excellent.  We'll have to try that out.

**Comment by luser** [comment] 2015-04-28 14:36
I spun up a droplet and was able to build and run the tests successfully. Unfortunately on the cheaper droplets it's pretty slow (I spun up their second-slowest one which is $10/month and it took ~66 minutes just to run the tests). Their droplets get pricey fast, but if I can get someone to volunteer their corp card I'd be happy to setup a jenkins instance on a slightly faster droplet to get automated tests running. I also filed a bug on making Taskcluster support DigitalOcean so that we could have it spin up droplets on-demand for testing, so that we could use faster instances without paying a ton of money: https://bugzilla.mozilla.org/show_bug.cgi?id=1159261 .

**Comment by luser** [comment] 2015-04-28 18:45
On a "16gb" droplet (16GB RAM, 8 CPUs), a full configure && make && make check took:
real	17m53.318s

**Comment by khuey** [comment] 2015-04-28 18:46
I spoke with @dherman and Mozilla Research can probably pick up the cost of the infra here directly.  We need to talk to him and Azita about it.

**Comment by luser** [comment] 2015-04-28 19:26
I've got Jenkins running on a droplet right now:
http://45.55.219.138:8080/job/rr/2/

It's not as fast as it could be because I'm only using an 8GB/4CPU droplet so my expense report doesn't look ridiculous, but it seems to be working. I'll see if I can get someone who's a Mozilla team owner to help me set up the webhooks to make this build per-push on the repo.

**Comment by luser** [comment] 2015-04-28 19:31
(lonnen added me to rr-committers so I'll make that happen tomorrow.)

**Comment by luser** [comment] 2015-04-28 21:13
That run build and ran tests, but a few of them failed:
``
The following tests FAILED:
	 73 - getsid (Failed)
	 74 - getsid-no-syscallbuf (Failed)
	637 - getsid-32 (Failed)
	638 - getsid-32-no-syscallbuf (Failed)
```

Anyone know what's up with that?

**Comment by froydnj** [comment] 2015-04-28 21:28
Do you have the logs from the test?

**Comment by rocallahan** [comment] 2015-04-28 21:42
I think we could just run `make fastcheck` for CI. That will skip the 32-bit tests and the no-syscallbuf tests, which is fine since those hardly ever used, and will take 1/4 of the time.

**Comment by luser** [comment] 2015-04-28 22:14
Logs are here btw: http://45.55.219.138:8080/job/rr/2/consoleText. I'll switch the build to use fastcheck.

**Comment by luser** [comment] 2015-04-28 22:50
getsid is still failing in fastcheck:
http://45.55.219.138:8080/job/rr/3/consoleText

**Comment by cgjones** [comment] 2015-04-29 01:02
Very cool, thanks!
```
37: Test 'getsid' FAILED: : token 'EXIT-SUCCESS' not in output:
37: --------------------------------------------------
37: getsid(0) session ID: 11054
37: getsid(getsid(0)) session ID: -1
37: --------------------------------------------------
```
No idea what's going on with the session IDs.  Maybe something to do with their virtualization setup?  Also it looks like the mismatch error message isn't being printed.

**Comment by rocallahan** [comment] 2015-04-29 01:23
I logged into the box and ran the test manually and it passed, so I'm not sure what the problem is. I pushed a change to getsid.c to report the errno when the test fails.

**Comment by luser** [comment] 2015-04-29 01:35
I triggered another build: http://45.55.219.138:8080/job/rr/4/console (I'll sort out auth on Jenkins so you can all do this as well tomorrow):
```
37: Test 'getsid' FAILED: : error during replay:
37: --------------------------------------------------
37: getsid-doJvUmJby: /var/lib/jenkins/workspace/rr/src/test/getsid.c:13: main: Assertion `"FAILED if not: " && (0)' failed.
37: --------------------------------------------------
37: Test getsid failed, leaving behind /tmp/rr-test-getsid-doJvUmJby.
37: To replay the failed test, run
37:   _RR_TRACE_DIR=/tmp/rr-test-getsid-doJvUmJby rr replay
  1/282 Test  #37: getsid ...................................***Failed  Error regular expression found in output. Regex=[FAILED]  0.71 sec
```

**Comment by luser** [comment] 2015-04-29 01:42
I configured the GitHub auth plugin, so you should be able to log in to Jenkins using GitHub and trigger new builds at least.

**Comment by rocallahan** [comment] 2015-04-29 03:58
Can you set up the github plugin so it doesn't require full read/write access to my github repos when I log in with my github account?

**Comment by rocallahan** [comment] 2015-04-29 04:17
Looks like what's happening is that the session leader is exited. In that case `getsid(getsid(0))` returns -1 with `ESRCH`. That's unusual but not wrong so I'll make the test tolerate that.

**Comment by rocallahan** [comment] 2015-04-29 04:26
Build is green ... well, blue. But it says "success".

**Comment by luser** [comment] 2015-04-29 10:50
@rocallahan Sorry about the auth plugin asking for everything under the sun, there's apparently a patch upstream to let you limit the permissions it asks for:
https://github.com/jenkinsci/github-oauth-plugin/pull/35

When that lands I'll update the plugin and set it to a more sensible set of permissions.

Hooray for a successful build! (I don't know why they use blue and not green, maybe for the benefit of colorblind users?)

**Comment by luser** [comment] 2015-04-29 10:53
Also, heh: http://jenkins-ci.org/content/why-does-jenkins-have-blue-balls

**Comment by luser** [comment] 2015-04-29 15:54
Okay, we've got per-push builds in Jenkins. I'm going to close this and open a new issue to track followup work.

**Closed by luser** 2015-04-29 15:54 UTC

**Comment by Keno** [comment] 2016-04-17 04:14
FWIW, Scaleway's x86 have PMUs enabled and are quite a bit more affordable.

**Comment by Keno** [comment] 2016-04-17 05:16
I unfortunately may have spoken to soon :(:
```
~/rr-build/bin/rr replay

rr: Warning: You appear to be running in a VMWare guest with a bug
    where a conditional branch instruction between two CPUID instructions
    sometimes fails to be counted by the conditional branch performance
    counter. Work around this problem by adding
        monitor_control.disable_hvsim_clusters = true
    to your .vmx file.

GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /root/.local/share/rr/latest-trace/mmap_hardlink_1_ls...(no debugging symbols found)...done.
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:4345
warning: limiting remote suggested packet size (17073526 bytes) to 16384
warning: remote target does not support file transfer, attempting to access files from local filesystem.
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.21.so...done.
done.
0x00007f9d0717ecd0 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) c
Continuing.
[FATAL /root/rr/src/ReplaySession.cc:760:check_ticks_consistency() errno: SUCCESS]
 (task 4346 (rec:4342) at time 25)
 -> Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SEGV_RDTSC'; expected 3, got 4
Launch gdb with
  gdb /root/.local/share/rr/latest-trace/mmap_hardlink_1_ls
and attach to the rr debug server with:
  target remote :4346
```
Looks like the perf counters may not be working as expected?

**Comment by rocallahan** [comment] 2016-04-21 02:26
Looks like Scaleway uses either bare metal or KVM. KVM works with rr on my Ivy Bridge and Skylake machines, so I'm not sure what the problem is. What sort of instance did you try?

**Comment by Keno** [comment] 2016-04-21 10:22
The problem is that it's silvermont.
